name = "vibesys"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
routes = ["api.7878.cloud"]

[vars]
FRONTEND_URL = "https://vibesys.7878.cloud,https://vibesys.pages.dev"
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "vibesysdb"
database_id = "eb62d282-41e8-4e75-af08-5ef3e2b6da59"
